resource_types:
- name: helm
  type: docker-image
  source:
    repository: kdvolder/concourse-helm-resource
resources:
- name: git
  type: git
  source:
    uri: https://github.com/nierajsingh/basic-greetings.git
    branch: master
- name: jdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
- name: docker-image
  type: docker-image
  source:
    repository: nsinghpivotal/basic-greetings
    tag: latest
    username: ((docker_user))
    password: ((docker_password))
- name: helm-release
  type: helm
  source:
    kube_config: ((kube_config))
    release: basic-greetings-master
jobs:
- name: build
  plan:
  - aggregate:
    - get: git
      trigger: true
    - get: jdk
  - task: build
    file: git/ci/tasks/build-fat-jar.yml
    image: jdk
  - put: docker-image
    params:
      build: out
    get_params:
      skip_download: true
- name: deploy
  plan:
  - aggregate:
    - get: git
    - get: docker-image
      passed:
      - build
      trigger: true
      params:
        skip_download: true       
  - put: helm-release
    params:
      chart: git/ci/helm
      recreate_pods: true
